name: Core Contrib Test

on:
  push:
    branches-ignore:
    - 'release/*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  contrib_0:
    uses: jomcgi/opentelemetry-python-contrib/.github/workflows/core_contrib_test_0.yml@bug-3352/fix-transient-ci-git-errors
    with:
      CORE_REPO_SHA: ${{ github.sha }}
      CONTRIB_REPO_SHA: 3f0886610c5bd4631dabb68394a8c48ac4b09fe1
